name: Deploy AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar chave SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy na EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
          
          cd app

          if [ ! -d "meuprojeto" ]; then
            git clone https://github.com/SEU_USUARIO/SEU_REPOSITORIO.git meuprojeto
          fi

          cd meuprojeto

          git pull origin main

          docker-compose down
          docker-compose up -d --build

          EOF